config/routes.rb
Gophermq::Application.routes.draw do    
  devise_for :users

  resources :users do
    resources :projects     
  end 

  match "/authenticate" => "projects#authenticate", :via => :post, :as => :authenticate

  scope "api" do
    scope "v1" do
      resources "docs", :only => :index, :controller => "api/v1/docs"
    end
  end

  resources :projects, :only => [] do
    resources :queues, :except => [:destroy], :controller => "gopher_queues" do
      match "/:queue_name", :to => "gopher_queues#destroy", :via => :delete, :on => :collection
      match "/:queue_name/notify", :to => "gopher_queues#notify", :via => :put, :as => :notify, :on => :collection
      match "/:queue_name/denotify", :to => "gopher_queues#denotify", :via => :put, :as => :denotify, :on => :collection
      match "/:queue_name/subscribe", :to => "gopher_queues#subscribe", :via => :put, :as => :subscribe, :on => :collection
      match "/:queue_name/unsubscribe", :to => "gopher_queues#unsubscribe", :via => :put, :as => :unsubscribe, :on => :collection         

      match "/:queue_name/subscriptions", :to => "subscriptions#create", :via => :post, :as => :subscriptions, :on => :collection
      match "/:queue_name/subscriptions/:id", :to => "subscriptions#destroy", :via => :delete, :as => :subscription, :on => :collection
      match "/:queue_name/subscriptions", :to => "subscriptions#index", :via => :get, :as => :subscriptions, :on => :collection
    end
  end

  match "/queues/:queue_name/jobs", :to => "jobs#index", :via => :get, :as => :queue_jobs  
  match "/queues/:queue_name/jobs", :to => "jobs#create", :via => :post, :as => :queue_jobs
  match "/queues/:queue_name/jobs/:id", :to => "jobs#destroy", :via => :delete, :as => :queue_job
  match "/queues/:queue_name/jobs/:id/fetch", :to => "jobs#fetch", :via => :get, :as => :fetch_queue_job
  match "/queues/:queue_name/jobs/list", :to => "jobs#list", :via => :get, :as => :list_queue_jobs

  

  root :to => "home#welcome", :as => :root

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/welcome.html.erb
<div class="jumbotron">
    <h1>Message Queues in the cloud</h1>
    <p class="lead">
    	Reliable, fast and easy to integrate cloud based message queues. And the we're free while were in Alpha.
    </p>
    <% if current_user.present? %>
    	<!-- <a class="btn btn-large btn-success" href="#">Create a new project</a> -->
    	<%= link_to "Create New Project", new_user_project_url(current_user), :class => "btn btn-large btn-success" %>
    <% else %>    	
    	<%= link_to "Signup for Free", new_user_registration_url, :class => "btn btn-large btn-success" %>
    <% end %>
</div>

<hr>

<div class="row-fluid">
    <div class="span4">
          <h2>REST apis</h2>
          <p>Easy to integrate REST APIs and client libraries that let you use GopherMQ from any kind of web application that requires message queues.</p>
          <p>
          	<a class="btn" href="#">View details »</a>
          </p>
    </div>
    <div class="span4">
	    <h2>Poll or Subscribe</h2>
    	<p>Poll using our REST APIs to fetch the latest messages or subscribe to a message queue and have the updates pushed via HTTP requests or our Socket API.  </p>
      	<p>
      		<a class="btn" href="#">View details »</a>
      	</p>
   </div>
    <div class="span4">
      	<h2>Dashboard</h2>
      	<p>Stay up to date and in control of every message and queue that you generate through a rich and easy interface. Delete or create queues, update messages and be notified of failures etc. </p>
      	<p>
      		<a class="btn" href="#">View details »</a>
      	</p>
    </div>
      </div>