config/routes.rb
Gophermq::Application.routes.draw do    
  devise_for :users

  resources :users do
    resources :projects     
  end 

  match "/authenticate" => "projects#authenticate", :via => :post, :as => :authenticate

  scope "api" do
    scope "v1" do
      resources "docs", :only => :index, :controller => "api/v1/docs"
    end
  end

  resources :projects, :only => [] do
    resources :queues, :except => [:destroy], :controller => "gopher_queues" do
      match "/:queue_name", :to => "gopher_queues#destroy", :via => :delete, :on => :collection
      match "/:queue_name/notify", :to => "gopher_queues#notify", :via => :put, :as => :notify, :on => :collection
      match "/:queue_name/denotify", :to => "gopher_queues#denotify", :via => :put, :as => :denotify, :on => :collection
      match "/:queue_name/subscribe", :to => "gopher_queues#subscribe", :via => :put, :as => :subscribe, :on => :collection
      match "/:queue_name/unsubscribe", :to => "gopher_queues#unsubscribe", :via => :put, :as => :unsubscribe, :on => :collection         

      match "/:queue_name/subscriptions", :to => "subscriptions#create", :via => :post, :as => :subscriptions, :on => :collection
      match "/:queue_name/subscriptions/:id", :to => "subscriptions#destroy", :via => :delete, :as => :subscription, :on => :collection
      match "/:queue_name/subscriptions", :to => "subscriptions#index", :via => :get, :as => :subscriptions, :on => :collection
    end
  end

  match "/queues/:queue_name/jobs", :to => "jobs#index", :via => :get, :as => :queue_jobs  
  match "/queues/:queue_name/jobs", :to => "jobs#create", :via => :post, :as => :queue_jobs
  match "/queues/:queue_name/jobs/:id", :to => "jobs#destroy", :via => :delete, :as => :queue_job
  match "/queues/:queue_name/jobs/:id/fetch", :to => "jobs#fetch", :via => :get, :as => :fetch_queue_job
  match "/queues/:queue_name/jobs/list", :to => "jobs#list", :via => :get, :as => :list_queue_jobs

  

  root :to => "home#welcome", :as => :root

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GopherMQ</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="masthead">
			<h3 class="muted"> GopherMQ</h3>
			<div class="navbar">
				<div class="navbar-inner">
					<div class="container">
						<ul class="nav">
							<li>
								<%= link_to "Home", root_url %>
							</li>
							<% if user_signed_in? %>
								<li>
									<%= link_to "Projects", user_projects_url(current_user) %>
								</li>
							<% end %>
							<li>
								<a href="#"> API </a>
							</li>
							<li>
								<a href="#"> Dashboard </a>
							</li>
							<li>
								<a href="#"> About </a>
							</li>
							<li>
								<a href="#"> Contact </a>
							</li>							
						</ul>
						
						<ul class="nav pull-right">
							<li>
								<% if user_signed_in? %>								
									<%= link_to "Logout", destroy_user_session_url, :method => :delete %>							
								<% else %>
									<%= link_to "SignIn/Register", new_user_registration_url %>									
								<% end %>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<%= render :partial => "shared/page_notification" %>
			<%= yield %>			
		</div>

		<div class="footer">
        	<p>©Idyllic Software 2013</p>
      </div>
	</div>
</body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GopherMQ</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="masthead">
			<h3 class="muted"> GopherMQ </h3>
			<div class="navbar">
				<div class="navbar-inner">
					<div class="container">
						<ul class="nav">
							<li>
								<a href="#" class="active"> Home </a>								
							</li>
							<li>
								<a href="#"> API </a>
							</li>
							<li>
								<a href="#"> Dashboard </a>
							</li>
							<li>
								<a href="#"> About </a>
							</li>
							<li>
								<a href="#"> Contact </a>
							</li>							
						</ul>
						
						<ul class="nav pull-right">
							<li>
								<% if user_signed_in? %>								
									<%= link_to "Logout", destroy_user_session_url, :method => :delete %>							
								<% else %>
									<%= link_to "SignIn/Register", new_user_registration_url %>									
								<% end %>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<%= yield %>
		</div>
	</div>
</body>
</html>